import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import MobileNav from "./components/MobileNav";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Theme> 
          <div className="flex">
            <div className="hidden lg:block bg-slate-200 p-4 w-64">
              <div className="sticky top-0">
                Desktop nav bar
              </div>
                
            </div>
            <div className="p-4 w-full flex items-center justify-around">
              {children}
            </div>
          </div> 
          </Theme>
        <MobileNav/>
      </body>
    </html>
  );
}
